# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/user/stargen

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/user/stargen

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/stargen/CMakeFiles /home/user/stargen//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/stargen/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/user/stargen/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named stargen

# Build rule for target.
stargen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stargen
.PHONY : stargen

# fast build rule for target.
stargen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/build
.PHONY : stargen/fast

#=============================================================================
# Target rules for targets named TracyClient

# Build rule for target.
TracyClient: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TracyClient
.PHONY : TracyClient

# fast build rule for target.
TracyClient/fast:
	$(MAKE) $(MAKESILENT) -f _deps/tracy-build/CMakeFiles/TracyClient.dir/build.make _deps/tracy-build/CMakeFiles/TracyClient.dir/build
.PHONY : TracyClient/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/Experimental.dir/build.make _deps/yaml-cpp-build/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/Nightly.dir/build.make _deps/yaml-cpp-build/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/Continuous.dir/build.make _deps/yaml-cpp-build/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/NightlyMemoryCheck.dir/build.make _deps/yaml-cpp-build/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/NightlyStart.dir/build.make _deps/yaml-cpp-build/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/NightlyUpdate.dir/build.make _deps/yaml-cpp-build/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/NightlyConfigure.dir/build.make _deps/yaml-cpp-build/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/NightlyBuild.dir/build.make _deps/yaml-cpp-build/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/NightlyTest.dir/build.make _deps/yaml-cpp-build/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/NightlyCoverage.dir/build.make _deps/yaml-cpp-build/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/NightlyMemCheck.dir/build.make _deps/yaml-cpp-build/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/NightlySubmit.dir/build.make _deps/yaml-cpp-build/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ExperimentalStart.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ExperimentalUpdate.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ExperimentalConfigure.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ExperimentalBuild.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ExperimentalTest.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ExperimentalCoverage.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ExperimentalMemCheck.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ExperimentalSubmit.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ContinuousStart.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ContinuousUpdate.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ContinuousConfigure.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ContinuousBuild.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ContinuousTest.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ContinuousCoverage.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ContinuousMemCheck.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ContinuousSubmit.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named yaml-cpp

# Build rule for target.
yaml-cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yaml-cpp
.PHONY : yaml-cpp

# fast build rule for target.
yaml-cpp/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/yaml-cpp.dir/build.make _deps/yaml-cpp-build/CMakeFiles/yaml-cpp.dir/build
.PHONY : yaml-cpp/fast

#=============================================================================
# Target rules for targets named format

# Build rule for target.
format: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 format
.PHONY : format

# fast build rule for target.
format/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/format.dir/build.make _deps/yaml-cpp-build/CMakeFiles/format.dir/build
.PHONY : format/fast

#=============================================================================
# Target rules for targets named yaml-cpp-sandbox

# Build rule for target.
yaml-cpp-sandbox: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yaml-cpp-sandbox
.PHONY : yaml-cpp-sandbox

# fast build rule for target.
yaml-cpp-sandbox/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-sandbox.dir/build.make _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-sandbox.dir/build
.PHONY : yaml-cpp-sandbox/fast

#=============================================================================
# Target rules for targets named yaml-cpp-parse

# Build rule for target.
yaml-cpp-parse: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yaml-cpp-parse
.PHONY : yaml-cpp-parse

# fast build rule for target.
yaml-cpp-parse/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-parse.dir/build.make _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-parse.dir/build
.PHONY : yaml-cpp-parse/fast

#=============================================================================
# Target rules for targets named yaml-cpp-read

# Build rule for target.
yaml-cpp-read: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yaml-cpp-read
.PHONY : yaml-cpp-read

# fast build rule for target.
yaml-cpp-read/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-read.dir/build.make _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-read.dir/build
.PHONY : yaml-cpp-read/fast

PerformanceMonitor.o: PerformanceMonitor.cpp.o
.PHONY : PerformanceMonitor.o

# target to build an object file
PerformanceMonitor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/PerformanceMonitor.cpp.o
.PHONY : PerformanceMonitor.cpp.o

PerformanceMonitor.i: PerformanceMonitor.cpp.i
.PHONY : PerformanceMonitor.i

# target to preprocess a source file
PerformanceMonitor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/PerformanceMonitor.cpp.i
.PHONY : PerformanceMonitor.cpp.i

PerformanceMonitor.s: PerformanceMonitor.cpp.s
.PHONY : PerformanceMonitor.s

# target to generate assembly for a file
PerformanceMonitor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/PerformanceMonitor.cpp.s
.PHONY : PerformanceMonitor.cpp.s

Planetary_Habitability_Laboratory.o: Planetary_Habitability_Laboratory.cpp.o
.PHONY : Planetary_Habitability_Laboratory.o

# target to build an object file
Planetary_Habitability_Laboratory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/Planetary_Habitability_Laboratory.cpp.o
.PHONY : Planetary_Habitability_Laboratory.cpp.o

Planetary_Habitability_Laboratory.i: Planetary_Habitability_Laboratory.cpp.i
.PHONY : Planetary_Habitability_Laboratory.i

# target to preprocess a source file
Planetary_Habitability_Laboratory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/Planetary_Habitability_Laboratory.cpp.i
.PHONY : Planetary_Habitability_Laboratory.cpp.i

Planetary_Habitability_Laboratory.s: Planetary_Habitability_Laboratory.cpp.s
.PHONY : Planetary_Habitability_Laboratory.s

# target to generate assembly for a file
Planetary_Habitability_Laboratory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/Planetary_Habitability_Laboratory.cpp.s
.PHONY : Planetary_Habitability_Laboratory.cpp.s

accrete.o: accrete.cpp.o
.PHONY : accrete.o

# target to build an object file
accrete.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/accrete.cpp.o
.PHONY : accrete.cpp.o

accrete.i: accrete.cpp.i
.PHONY : accrete.i

# target to preprocess a source file
accrete.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/accrete.cpp.i
.PHONY : accrete.cpp.i

accrete.s: accrete.cpp.s
.PHONY : accrete.s

# target to generate assembly for a file
accrete.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/accrete.cpp.s
.PHONY : accrete.cpp.s

andromeda.o: andromeda.cpp.o
.PHONY : andromeda.o

# target to build an object file
andromeda.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/andromeda.cpp.o
.PHONY : andromeda.cpp.o

andromeda.i: andromeda.cpp.i
.PHONY : andromeda.i

# target to preprocess a source file
andromeda.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/andromeda.cpp.i
.PHONY : andromeda.cpp.i

andromeda.s: andromeda.cpp.s
.PHONY : andromeda.s

# target to generate assembly for a file
andromeda.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/andromeda.cpp.s
.PHONY : andromeda.cpp.s

andromeda2.o: andromeda2.cpp.o
.PHONY : andromeda2.o

# target to build an object file
andromeda2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/andromeda2.cpp.o
.PHONY : andromeda2.cpp.o

andromeda2.i: andromeda2.cpp.i
.PHONY : andromeda2.i

# target to preprocess a source file
andromeda2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/andromeda2.cpp.i
.PHONY : andromeda2.cpp.i

andromeda2.s: andromeda2.cpp.s
.PHONY : andromeda2.s

# target to generate assembly for a file
andromeda2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/andromeda2.cpp.s
.PHONY : andromeda2.cpp.s

display.o: display.cpp.o
.PHONY : display.o

# target to build an object file
display.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/display.cpp.o
.PHONY : display.cpp.o

display.i: display.cpp.i
.PHONY : display.i

# target to preprocess a source file
display.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/display.cpp.i
.PHONY : display.cpp.i

display.s: display.cpp.s
.PHONY : display.s

# target to generate assembly for a file
display.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/display.cpp.s
.PHONY : display.cpp.s

dole.o: dole.cpp.o
.PHONY : dole.o

# target to build an object file
dole.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/dole.cpp.o
.PHONY : dole.cpp.o

dole.i: dole.cpp.i
.PHONY : dole.i

# target to preprocess a source file
dole.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/dole.cpp.i
.PHONY : dole.cpp.i

dole.s: dole.cpp.s
.PHONY : dole.s

# target to generate assembly for a file
dole.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/dole.cpp.s
.PHONY : dole.cpp.s

elements.o: elements.cpp.o
.PHONY : elements.o

# target to build an object file
elements.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/elements.cpp.o
.PHONY : elements.cpp.o

elements.i: elements.cpp.i
.PHONY : elements.i

# target to preprocess a source file
elements.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/elements.cpp.i
.PHONY : elements.cpp.i

elements.s: elements.cpp.s
.PHONY : elements.s

# target to generate assembly for a file
elements.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/elements.cpp.s
.PHONY : elements.cpp.s

enviro.o: enviro.cpp.o
.PHONY : enviro.o

# target to build an object file
enviro.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/enviro.cpp.o
.PHONY : enviro.cpp.o

enviro.i: enviro.cpp.i
.PHONY : enviro.i

# target to preprocess a source file
enviro.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/enviro.cpp.i
.PHONY : enviro.cpp.i

enviro.s: enviro.cpp.s
.PHONY : enviro.s

# target to generate assembly for a file
enviro.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/enviro.cpp.s
.PHONY : enviro.cpp.s

gas_radius_helpers.o: gas_radius_helpers.cpp.o
.PHONY : gas_radius_helpers.o

# target to build an object file
gas_radius_helpers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/gas_radius_helpers.cpp.o
.PHONY : gas_radius_helpers.cpp.o

gas_radius_helpers.i: gas_radius_helpers.cpp.i
.PHONY : gas_radius_helpers.i

# target to preprocess a source file
gas_radius_helpers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/gas_radius_helpers.cpp.i
.PHONY : gas_radius_helpers.cpp.i

gas_radius_helpers.s: gas_radius_helpers.cpp.s
.PHONY : gas_radius_helpers.s

# target to generate assembly for a file
gas_radius_helpers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/gas_radius_helpers.cpp.s
.PHONY : gas_radius_helpers.cpp.s

ic3094.o: ic3094.cpp.o
.PHONY : ic3094.o

# target to build an object file
ic3094.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/ic3094.cpp.o
.PHONY : ic3094.cpp.o

ic3094.i: ic3094.cpp.i
.PHONY : ic3094.i

# target to preprocess a source file
ic3094.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/ic3094.cpp.i
.PHONY : ic3094.cpp.i

ic3094.s: ic3094.cpp.s
.PHONY : ic3094.s

# target to generate assembly for a file
ic3094.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/ic3094.cpp.s
.PHONY : ic3094.cpp.s

ic3094_2.o: ic3094_2.cpp.o
.PHONY : ic3094_2.o

# target to build an object file
ic3094_2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/ic3094_2.cpp.o
.PHONY : ic3094_2.cpp.o

ic3094_2.i: ic3094_2.cpp.i
.PHONY : ic3094_2.i

# target to preprocess a source file
ic3094_2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/ic3094_2.cpp.i
.PHONY : ic3094_2.cpp.i

ic3094_2.s: ic3094_2.cpp.s
.PHONY : ic3094_2.s

# target to generate assembly for a file
ic3094_2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/ic3094_2.cpp.s
.PHONY : ic3094_2.cpp.s

jimb.o: jimb.cpp.o
.PHONY : jimb.o

# target to build an object file
jimb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/jimb.cpp.o
.PHONY : jimb.cpp.o

jimb.i: jimb.cpp.i
.PHONY : jimb.i

# target to preprocess a source file
jimb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/jimb.cpp.i
.PHONY : jimb.cpp.i

jimb.s: jimb.cpp.s
.PHONY : jimb.s

# target to generate assembly for a file
jimb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/jimb.cpp.s
.PHONY : jimb.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/main.cpp.s
.PHONY : main.cpp.s

omega_galaxy.o: omega_galaxy.cpp.o
.PHONY : omega_galaxy.o

# target to build an object file
omega_galaxy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/omega_galaxy.cpp.o
.PHONY : omega_galaxy.cpp.o

omega_galaxy.i: omega_galaxy.cpp.i
.PHONY : omega_galaxy.i

# target to preprocess a source file
omega_galaxy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/omega_galaxy.cpp.i
.PHONY : omega_galaxy.cpp.i

omega_galaxy.s: omega_galaxy.cpp.s
.PHONY : omega_galaxy.s

# target to generate assembly for a file
omega_galaxy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/omega_galaxy.cpp.s
.PHONY : omega_galaxy.cpp.s

omega_galaxy2.o: omega_galaxy2.cpp.o
.PHONY : omega_galaxy2.o

# target to build an object file
omega_galaxy2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/omega_galaxy2.cpp.o
.PHONY : omega_galaxy2.cpp.o

omega_galaxy2.i: omega_galaxy2.cpp.i
.PHONY : omega_galaxy2.i

# target to preprocess a source file
omega_galaxy2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/omega_galaxy2.cpp.i
.PHONY : omega_galaxy2.cpp.i

omega_galaxy2.s: omega_galaxy2.cpp.s
.PHONY : omega_galaxy2.s

# target to generate assembly for a file
omega_galaxy2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/omega_galaxy2.cpp.s
.PHONY : omega_galaxy2.cpp.s

planets.o: planets.cpp.o
.PHONY : planets.o

# target to build an object file
planets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/planets.cpp.o
.PHONY : planets.cpp.o

planets.i: planets.cpp.i
.PHONY : planets.i

# target to preprocess a source file
planets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/planets.cpp.i
.PHONY : planets.cpp.i

planets.s: planets.cpp.s
.PHONY : planets.s

# target to generate assembly for a file
planets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/planets.cpp.s
.PHONY : planets.cpp.s

radius_tables.o: radius_tables.cpp.o
.PHONY : radius_tables.o

# target to build an object file
radius_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/radius_tables.cpp.o
.PHONY : radius_tables.cpp.o

radius_tables.i: radius_tables.cpp.i
.PHONY : radius_tables.i

# target to preprocess a source file
radius_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/radius_tables.cpp.i
.PHONY : radius_tables.cpp.i

radius_tables.s: radius_tables.cpp.s
.PHONY : radius_tables.s

# target to generate assembly for a file
radius_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/radius_tables.cpp.s
.PHONY : radius_tables.cpp.s

ring_universe.o: ring_universe.cpp.o
.PHONY : ring_universe.o

# target to build an object file
ring_universe.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/ring_universe.cpp.o
.PHONY : ring_universe.cpp.o

ring_universe.i: ring_universe.cpp.i
.PHONY : ring_universe.i

# target to preprocess a source file
ring_universe.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/ring_universe.cpp.i
.PHONY : ring_universe.cpp.i

ring_universe.s: ring_universe.cpp.s
.PHONY : ring_universe.s

# target to generate assembly for a file
ring_universe.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/ring_universe.cpp.s
.PHONY : ring_universe.cpp.s

solid_radius_helpers.o: solid_radius_helpers.cpp.o
.PHONY : solid_radius_helpers.o

# target to build an object file
solid_radius_helpers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/solid_radius_helpers.cpp.o
.PHONY : solid_radius_helpers.cpp.o

solid_radius_helpers.i: solid_radius_helpers.cpp.i
.PHONY : solid_radius_helpers.i

# target to preprocess a source file
solid_radius_helpers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/solid_radius_helpers.cpp.i
.PHONY : solid_radius_helpers.cpp.i

solid_radius_helpers.s: solid_radius_helpers.cpp.s
.PHONY : solid_radius_helpers.s

# target to generate assembly for a file
solid_radius_helpers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/solid_radius_helpers.cpp.s
.PHONY : solid_radius_helpers.cpp.s

solstation.o: solstation.cpp.o
.PHONY : solstation.o

# target to build an object file
solstation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/solstation.cpp.o
.PHONY : solstation.cpp.o

solstation.i: solstation.cpp.i
.PHONY : solstation.i

# target to preprocess a source file
solstation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/solstation.cpp.i
.PHONY : solstation.cpp.i

solstation.s: solstation.cpp.s
.PHONY : solstation.s

# target to generate assembly for a file
solstation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/solstation.cpp.s
.PHONY : solstation.cpp.s

star_temps.o: star_temps.cpp.o
.PHONY : star_temps.o

# target to build an object file
star_temps.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/star_temps.cpp.o
.PHONY : star_temps.cpp.o

star_temps.i: star_temps.cpp.i
.PHONY : star_temps.i

# target to preprocess a source file
star_temps.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/star_temps.cpp.i
.PHONY : star_temps.cpp.i

star_temps.s: star_temps.cpp.s
.PHONY : star_temps.s

# target to generate assembly for a file
star_temps.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/star_temps.cpp.s
.PHONY : star_temps.cpp.s

star_trek.o: star_trek.cpp.o
.PHONY : star_trek.o

# target to build an object file
star_trek.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/star_trek.cpp.o
.PHONY : star_trek.cpp.o

star_trek.i: star_trek.cpp.i
.PHONY : star_trek.i

# target to preprocess a source file
star_trek.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/star_trek.cpp.i
.PHONY : star_trek.cpp.i

star_trek.s: star_trek.cpp.s
.PHONY : star_trek.s

# target to generate assembly for a file
star_trek.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/star_trek.cpp.s
.PHONY : star_trek.cpp.s

stargen.o: stargen.cpp.o
.PHONY : stargen.o

# target to build an object file
stargen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/stargen.cpp.o
.PHONY : stargen.cpp.o

stargen.i: stargen.cpp.i
.PHONY : stargen.i

# target to preprocess a source file
stargen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/stargen.cpp.i
.PHONY : stargen.cpp.i

stargen.s: stargen.cpp.s
.PHONY : stargen.s

# target to generate assembly for a file
stargen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/stargen.cpp.s
.PHONY : stargen.cpp.s

structs.o: structs.cpp.o
.PHONY : structs.o

# target to build an object file
structs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/structs.cpp.o
.PHONY : structs.cpp.o

structs.i: structs.cpp.i
.PHONY : structs.i

# target to preprocess a source file
structs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/structs.cpp.i
.PHONY : structs.cpp.i

structs.s: structs.cpp.s
.PHONY : structs.s

# target to generate assembly for a file
structs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/structs.cpp.s
.PHONY : structs.cpp.s

utils.o: utils.cpp.o
.PHONY : utils.o

# target to build an object file
utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/utils.cpp.o
.PHONY : utils.cpp.o

utils.i: utils.cpp.i
.PHONY : utils.i

# target to preprocess a source file
utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/utils.cpp.i
.PHONY : utils.cpp.i

utils.s: utils.cpp.s
.PHONY : utils.s

# target to generate assembly for a file
utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stargen.dir/build.make CMakeFiles/stargen.dir/utils.cpp.s
.PHONY : utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... format"
	@echo "... TracyClient"
	@echo "... stargen"
	@echo "... yaml-cpp"
	@echo "... yaml-cpp-parse"
	@echo "... yaml-cpp-read"
	@echo "... yaml-cpp-sandbox"
	@echo "... PerformanceMonitor.o"
	@echo "... PerformanceMonitor.i"
	@echo "... PerformanceMonitor.s"
	@echo "... Planetary_Habitability_Laboratory.o"
	@echo "... Planetary_Habitability_Laboratory.i"
	@echo "... Planetary_Habitability_Laboratory.s"
	@echo "... accrete.o"
	@echo "... accrete.i"
	@echo "... accrete.s"
	@echo "... andromeda.o"
	@echo "... andromeda.i"
	@echo "... andromeda.s"
	@echo "... andromeda2.o"
	@echo "... andromeda2.i"
	@echo "... andromeda2.s"
	@echo "... display.o"
	@echo "... display.i"
	@echo "... display.s"
	@echo "... dole.o"
	@echo "... dole.i"
	@echo "... dole.s"
	@echo "... elements.o"
	@echo "... elements.i"
	@echo "... elements.s"
	@echo "... enviro.o"
	@echo "... enviro.i"
	@echo "... enviro.s"
	@echo "... gas_radius_helpers.o"
	@echo "... gas_radius_helpers.i"
	@echo "... gas_radius_helpers.s"
	@echo "... ic3094.o"
	@echo "... ic3094.i"
	@echo "... ic3094.s"
	@echo "... ic3094_2.o"
	@echo "... ic3094_2.i"
	@echo "... ic3094_2.s"
	@echo "... jimb.o"
	@echo "... jimb.i"
	@echo "... jimb.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... omega_galaxy.o"
	@echo "... omega_galaxy.i"
	@echo "... omega_galaxy.s"
	@echo "... omega_galaxy2.o"
	@echo "... omega_galaxy2.i"
	@echo "... omega_galaxy2.s"
	@echo "... planets.o"
	@echo "... planets.i"
	@echo "... planets.s"
	@echo "... radius_tables.o"
	@echo "... radius_tables.i"
	@echo "... radius_tables.s"
	@echo "... ring_universe.o"
	@echo "... ring_universe.i"
	@echo "... ring_universe.s"
	@echo "... solid_radius_helpers.o"
	@echo "... solid_radius_helpers.i"
	@echo "... solid_radius_helpers.s"
	@echo "... solstation.o"
	@echo "... solstation.i"
	@echo "... solstation.s"
	@echo "... star_temps.o"
	@echo "... star_temps.i"
	@echo "... star_temps.s"
	@echo "... star_trek.o"
	@echo "... star_trek.i"
	@echo "... star_trek.s"
	@echo "... stargen.o"
	@echo "... stargen.i"
	@echo "... stargen.s"
	@echo "... structs.o"
	@echo "... structs.i"
	@echo "... structs.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/user/stargen/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

