#ifndef SIMULATION_CONTEXT_H
#define SIMULATION_CONTEXT_H

#include <atomic>
#include <mutex>
#include "structs.h"

/**
 * @brief Thread-safe simulation context to hold runtime state and statistics
 *
 * This class replaces the global state variables previously in stargen.h.
 * It maintains statistics about generated systems and runtime state that
 * changes during simulation execution.
 *
 * Thread Safety:
 * - Integer counters use std::atomic for lock-free thread safety
 * - Min/max tracking uses mutex protection (long double not always lock-free)
 * - Per-system statistics are not thread-safe (single-threaded per system)
 */
class SimulationContext {
public:
    // Clone of the current sun (for context sharing)
    sun current_sun;

    // Planet generation state
    planet* innermost_planet = nullptr;  // DEPRECATED: Use planets vector instead
    std::vector<planet*> planets;  // Vector of planets (replacing linked list)
    std::vector<planet*> moons_cache; // Temporary cache for moon processing
    long double dust_density_coeff = 0.0;  // Dust density coefficient for accretion
    long current_system_seed = 0;  // Seed for current system being generated
    int system_counter = 0;  // Counter for number of systems generated

    // Global/cross-system statistics counters (thread-safe with atomics)
    std::atomic<int> total_earthlike{0};
    std::atomic<int> total_habitable{0};
    std::atomic<int> total_habitable_earthlike{0};
    std::atomic<int> total_habitable_conservative{0};
    std::atomic<int> total_habitable_optimistic{0};
    std::atomic<int> total_potentially_habitable{0};
    std::atomic<int> total_potentially_habitable_earthlike{0};
    std::atomic<int> total_potentially_habitable_conservative{0};
    std::atomic<int> total_potentially_habitable_optimistic{0};
    std::atomic<int> total_worlds{0};

    // Per-system statistics (NOT thread-safe - each system generated by single thread)
    int system_earthlike = 0;
    int system_habitable = 0;
    int system_habitable_jovians = 0;
    int system_habitable_superterrans = 0;
    int system_potentially_habitable = 0;
    long double system_max_moon_mass = 0.0;

    // Type diversity tracking (NOT thread-safe - per-system only)
    int type_counts[16] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    int type_count = 0;
    int max_type_count = 0;

    // Breathable planet statistics (min/max values)
    // Min values initialized high so first real value will be less
    // NOTE: Direct access is DEPRECATED and NOT thread-safe!
    // Use updateBreathableStats() for thread-safe updates
    // Use getBreathableStats() for thread-safe reads
    long double min_breathable_terrestrial_g = 1000.0;
    long double min_breathable_g = 1000.0;
    long double max_breathable_terrestrial_g = 0.0;
    long double max_breathable_g = 0.0;
    long double min_breathable_terrestrial_l = 1000.0;
    long double min_breathable_l = 1000.0;
    long double max_breathable_terrestrial_l = 0.0;
    long double max_breathable_l = 0.0;
    long double min_breathable_temp = 1000.0;
    long double max_breathable_temp = 0.0;
    long double min_breathable_p = 100000.0;
    long double max_breathable_p = 0.0;
    long double min_breathable_mass = 0.0;
    long double max_breathable_mass = 0.0;

    // Potentially habitable planet statistics (min/max values)
    // Min values initialized high so first real value will be less
    // NOTE: Direct access is DEPRECATED and NOT thread-safe!
    // Use updatePotentialStats() for thread-safe updates
    // Use getPotentialStats() for thread-safe reads
    long double min_potential_terrestrial_g = 1000.0;
    long double min_potential_g = 1000.0;
    long double max_potential_terrestrial_g = 0.0;
    long double max_potential_g = 0.0;
    long double min_potential_terrestrial_l = 1000.0;
    long double min_potential_l = 1000.0;
    long double max_potential_terrestrial_l = 0.0;
    long double max_potential_l = 0.0;
    long double min_potential_temp = 1000.0;
    long double max_potential_temp = 0.0;
    long double min_potential_p = 100000.0;
    long double max_potential_p = 0.0;
    long double min_potential_mass = 0.0;
    long double max_potential_mass = 0.0;

private:
    // Mutex for protecting min/max statistics (long double not always lock-free)
    mutable std::mutex stats_mutex;

public:
    SimulationContext() = default;

    // Helper methods for statistics (thread-safe)
    void recordEarthlike() {
        total_earthlike.fetch_add(1, std::memory_order_relaxed);
        system_earthlike++;  // Per-system stat, not thread-safe
    }

    void recordHabitable() {
        total_habitable.fetch_add(1, std::memory_order_relaxed);
        system_habitable++;  // Per-system stat, not thread-safe
    }

    void recordWorld() {
        total_worlds.fetch_add(1, std::memory_order_relaxed);
    }

    void resetGlobalStatistics() {
        total_earthlike.store(0, std::memory_order_relaxed);
        total_habitable.store(0, std::memory_order_relaxed);
        total_habitable_earthlike.store(0, std::memory_order_relaxed);
        total_habitable_conservative.store(0, std::memory_order_relaxed);
        total_habitable_optimistic.store(0, std::memory_order_relaxed);
        total_potentially_habitable.store(0, std::memory_order_relaxed);
        total_potentially_habitable_earthlike.store(0, std::memory_order_relaxed);
        total_potentially_habitable_conservative.store(0, std::memory_order_relaxed);
        total_potentially_habitable_optimistic.store(0, std::memory_order_relaxed);
        total_worlds.store(0, std::memory_order_relaxed);
    }

    void resetSystemStatistics() {
        system_earthlike = 0;
        system_habitable = 0;
        system_habitable_jovians = 0;
        system_habitable_superterrans = 0;
        system_potentially_habitable = 0;
        system_max_moon_mass = 0.0;

        // Reset type diversity tracking
        for (int i = 0; i < 16; i++) {
            type_counts[i] = 0;
        }
        type_count = 0;
        max_type_count = 0;
    }

    // Backward compatibility alias
    void resetStatistics() {
        resetGlobalStatistics();
    }

    // Planet vector management
    void buildPlanetVector() {
        planets.clear();
        for (planet* p = innermost_planet; p != nullptr; p = p->next_planet) {
            planets.push_back(p);
        }
    }

    void clearPlanets() {
        planets.clear();
        innermost_planet = nullptr;
    }

    // Get planet count
    size_t getPlanetCount() const {
        return planets.size();
    }

    // Thread-safe update of breathable planet statistics
    void updateBreathableStats(long double g, long double l, long double temp,
                               long double p, long double mass, bool is_terrestrial) {
        std::lock_guard<std::mutex> lock(stats_mutex);

        // Update min/max for all breathable planets
        if (min_breathable_g == 0.0 || g < min_breathable_g) min_breathable_g = g;
        if (g > max_breathable_g) max_breathable_g = g;
        if (min_breathable_l == 0.0 || l < min_breathable_l) min_breathable_l = l;
        if (l > max_breathable_l) max_breathable_l = l;
        if (min_breathable_temp == 0.0 || temp < min_breathable_temp) min_breathable_temp = temp;
        if (temp > max_breathable_temp) max_breathable_temp = temp;
        if (min_breathable_p == 0.0 || p < min_breathable_p) min_breathable_p = p;
        if (p > max_breathable_p) max_breathable_p = p;
        if (min_breathable_mass == 0.0 || mass < min_breathable_mass) min_breathable_mass = mass;
        if (mass > max_breathable_mass) max_breathable_mass = mass;

        // Update terrestrial-specific stats
        if (is_terrestrial) {
            if (min_breathable_terrestrial_g == 0.0 || g < min_breathable_terrestrial_g)
                min_breathable_terrestrial_g = g;
            if (g > max_breathable_terrestrial_g) max_breathable_terrestrial_g = g;
            if (min_breathable_terrestrial_l == 0.0 || l < min_breathable_terrestrial_l)
                min_breathable_terrestrial_l = l;
            if (l > max_breathable_terrestrial_l) max_breathable_terrestrial_l = l;
        }
    }

    // Thread-safe update of potentially habitable planet statistics
    void updatePotentialStats(long double g, long double l, long double temp,
                             long double p, long double mass, bool is_terrestrial) {
        std::lock_guard<std::mutex> lock(stats_mutex);

        // Update min/max for all potentially habitable planets
        if (min_potential_g == 0.0 || g < min_potential_g) min_potential_g = g;
        if (g > max_potential_g) max_potential_g = g;
        if (min_potential_l == 0.0 || l < min_potential_l) min_potential_l = l;
        if (l > max_potential_l) max_potential_l = l;
        if (min_potential_temp == 0.0 || temp < min_potential_temp) min_potential_temp = temp;
        if (temp > max_potential_temp) max_potential_temp = temp;
        if (min_potential_p == 0.0 || p < min_potential_p) min_potential_p = p;
        if (p > max_potential_p) max_potential_p = p;
        if (min_potential_mass == 0.0 || mass < min_potential_mass) min_potential_mass = mass;
        if (mass > max_potential_mass) max_potential_mass = mass;

        // Update terrestrial-specific stats
        if (is_terrestrial) {
            if (min_potential_terrestrial_g == 0.0 || g < min_potential_terrestrial_g)
                min_potential_terrestrial_g = g;
            if (g > max_potential_terrestrial_g) max_potential_terrestrial_g = g;
            if (min_potential_terrestrial_l == 0.0 || l < min_potential_terrestrial_l)
                min_potential_terrestrial_l = l;
            if (l > max_potential_terrestrial_l) max_potential_terrestrial_l = l;
        }
    }

    // Thread-safe getters for statistics (for output/display)
    int getTotalEarthlike() const { return total_earthlike.load(std::memory_order_relaxed); }
    int getTotalHabitable() const { return total_habitable.load(std::memory_order_relaxed); }
    int getTotalWorlds() const { return total_worlds.load(std::memory_order_relaxed); }

    // Get breathable stats (requires lock)
    void getBreathableStats(long double& min_g, long double& max_g,
                           long double& min_l, long double& max_l,
                           long double& min_t, long double& max_t) const {
        std::lock_guard<std::mutex> lock(stats_mutex);
        min_g = min_breathable_g;
        max_g = max_breathable_g;
        min_l = min_breathable_l;
        max_l = max_breathable_l;
        min_t = min_breathable_temp;
        max_t = max_breathable_temp;
    }

    // Get potential stats (requires lock)
    void getPotentialStats(long double& min_g, long double& max_g,
                          long double& min_l, long double& max_l,
                          long double& min_t, long double& max_t) const {
        std::lock_guard<std::mutex> lock(stats_mutex);
        min_g = min_potential_g;
        max_g = max_potential_g;
        min_l = min_potential_l;
        max_l = max_potential_l;
        min_t = min_potential_temp;
        max_t = max_potential_temp;
    }
};

#endif // SIMULATION_CONTEXT_H
