# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ring_universe.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'ring_universe.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13ring_universe.proto\"\xc3\x02\n\rRing_universe\x12+\n\x05items\x18\x01 \x03(\x0b\x32\x1c.Ring_universe.Ring_universe\x1a\x84\x02\n\rRing_universe\x12\x12\n\nLuminosity\x18\x01 \x01(\x02\x12\x0c\n\x04Mass\x18\x02 \x01(\x02\x12\r\n\x05Mass2\x18\x03 \x01(\x05\x12\x14\n\x0cSpectralType\x18\x04 \x01(\t\x12\x14\n\x0c\x45\x63\x63\x65ntricity\x18\x05 \x01(\x05\x12\x15\n\rSemiMajorAxis\x18\x06 \x01(\x05\x12\x0f\n\x07Planets\x18\x07 \x01(\x05\x12\x17\n\x0f\x44\x65signationCode\x18\x08 \x01(\x05\x12\x16\n\x0e\x41\x64\x64itionalCode\x18\t \x01(\x05\x12\x13\n\x0b\x44\x65signation\x18\n \x01(\t\x12\x15\n\rInCelNameCode\x18\x0b \x01(\x05\x12\x11\n\tInCelName\x18\x0c \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ring_universe_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RING_UNIVERSE']._serialized_start=24
  _globals['_RING_UNIVERSE']._serialized_end=347
  _globals['_RING_UNIVERSE_RING_UNIVERSE']._serialized_start=87
  _globals['_RING_UNIVERSE_RING_UNIVERSE']._serialized_end=347
# @@protoc_insertion_point(module_scope)
